ruby '2.2.2'

source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'rails', '4.1.8'
gem 'activejob'
gem 'elasticsearch-persistence'
gem 'warden'
gem 'bcrypt'
gem 'state_machine'
gem 'high_voltage'
gem 'excon'
gem 'gon'
gem 'stringex'
gem 'slim-rails'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'russian'
gem 'aws-sdk'
gem 'newrelic_rpm'
gem 'puma'
gem 'rails_12factor'
